/**
 * Build-time data access.
 *
 * These files are produced by the pipeline in scripts/. Placeholder versions
 * generated by tools/make-placeholder-data.mjs are committed so the site always
 * builds; they carry `placeholder: true`, which the UI surfaces.
 *
 * The same files are served from public/data/ and re-polled by the client every
 * 120 seconds so a page left open picks up a newer pipeline run.
 */

import rankingsJson from '../data/rankings.json';
import newsJson from '../data/news.json';
import performanceJson from '../data/performance.json';
import sectorsJson from '../data/sectors.json';
import healthJson from '../data/health.json';

import type { Health, News, Performance, Rankings, Sectors } from './types';

export const rankings = rankingsJson as unknown as Rankings;
export const news = newsJson as unknown as News;
export const performance = performanceJson as unknown as Performance;
export const sectors = sectorsJson as unknown as Sectors;
export const health = healthJson as unknown as Health;

export type DatasetName = 'rankings' | 'news' | 'performance' | 'sectors' | 'health';

/**
 * Per-dataset placeholder state.
 *
 * The pipeline stages run independently — a run can produce real rankings while
 * the news fetcher is still blocked by the sandbox's network policy — so a
 * page-wide "everything here is fake" banner goes stale the moment any one
 * stage succeeds. A warning that is wrong in a checkable way teaches readers to
 * ignore warnings, so this is tracked per file and reported per file.
 */
export const placeholderStatus: Record<DatasetName, boolean> = {
  rankings: Boolean(rankings.placeholder),
  news: Boolean(news.placeholder),
  performance: Boolean(performance.placeholder),
  sectors: Boolean(sectors.placeholder),
  health: Boolean(health.placeholder),
};

/** Which of the given datasets are placeholder / real. */
export function splitPlaceholder(datasets: DatasetName[]) {
  const placeholder = datasets.filter((d) => placeholderStatus[d]);
  const real = datasets.filter((d) => !placeholderStatus[d]);
  return { placeholder, real };
}

/** True when ANY dataset in the build is still placeholder output. */
export const isPlaceholder = (Object.values(placeholderStatus) as boolean[]).some(Boolean);

/** Each dataset's own generation timestamp, so the client can tell per file
 *  whether the published data has actually moved since this page was built. */
export const datasetGeneratedAt: Record<DatasetName, string> = {
  rankings: rankings.generatedAt,
  news: news.generatedAt,
  performance: performance.generatedAt,
  sectors: sectors.generatedAt,
  health: health.generatedAt,
};

/** Newest generation timestamp across all datasets — used for the footer stamp. */
export const dataGeneratedAt = [
  rankings.generatedAt,
  news.generatedAt,
  performance.generatedAt,
  sectors.generatedAt,
]
  .filter(Boolean)
  .sort()
  .pop() as string;

/** How often the client re-polls public/data/*.json, in milliseconds. */
export const REFRESH_MS = 120_000;
